# Extracting Muon Position From Asymmetry Data

## High Level Idea:
1. Keep events for L1 channel 11 (asymmetry cut1)
1. Keep events for L1 channel 1 (asymmetry cut1)

In [3]:
from MuonDataFrame import *
ifile = "processed_data/events_data_frame_801.ftr"
mdfo = MuonDataFrame(ifile, isNew=False, d1="last")

In [4]:
mdf = mdfo.events_df

In [7]:
mdfo.keepEvents("asymL1", 0.21, ">=")
mdf1 = mdfo.events_df

In [8]:
mdf1

,event_num,event_time,deadtime,ADC,TDC,SCh0,SCh1,SCh2,SCh3,SCh4,...,sumL4,diffL1,diffL2,diffL3,diffL4,asymL1,asymL2,asymL3,asymL4,numLHit
139,139,2020-10-16 17:33:12.262549,839,"[1, 31, 33, 33, 29, 21, 27, 6, 7, 16, 16, 23]","[[0, 127], [1, 77], [3, 90], [4, 125], [9, 116...",1,28,27,0,9,...,231.0,50.0,-35.0,NaN,1.0,0.245098,-0.162791,NaN,0.004329,6
300,300,2020-10-16 17:33:54.416732,1104,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 115], [1, 73], [3, 126], [4, 82], [6, 115...",1,7,12,0,3,...,NaN,42.0,44.0,24.0,NaN,0.223404,0.211538,0.116505,NaN,7
467,467,2020-10-16 17:34:35.381299,1249,"[1, 32, 33, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 118], [1, 68], [3, 124], [4, 110], [6, 12...",1,15,29,0,5,...,251.0,50.0,14.0,41.0,3.0,0.268817,0.059829,0.201970,0.011952,8
495,495,2020-10-16 17:34:43.042057,3399,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 122], [1, 73], [3, 84], [4, 117], [9, 130]]",1,37,47,0,19,...,NaN,49.0,-33.0,NaN,NaN,0.251282,-0.164179,NaN,NaN,5
566,566,2020-10-16 17:35:02.334107,3326,"[1, 35, 36, 37, 33, 24, 30, 9, 10, 20, 20, 26]","[[0, 121], [1, 78], [3, 110], [4, 110], [6, 12...",1,56,77,0,18,...,NaN,43.0,0.0,33.0,NaN,0.216080,0.000000,0.159420,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199853,199853,2020-10-17 06:47:36.119947,1225,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 123], [1, 80], [3, 87], [4, 121], [6, 126...",1,28,27,0,4,...,215.0,43.0,-34.0,42.0,43.0,0.211823,-0.163462,0.200000,0.200000,8
199880,199880,2020-10-17 06:47:42.660912,1369,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 121], [1, 77], [3, 80], [4, 123], [6, 120...",1,28,35,0,17,...,208.0,44.0,-43.0,34.0,46.0,0.222222,-0.211823,0.165049,0.221154,8
199902,199902,2020-10-17 06:47:47.971304,819,"[1, 31, 32, 33, 29, 21, 27, 6, 7, 16, 16, 23]","[[0, 117], [1, 75], [3, 121], [4, 87]]",1,40,54,0,12,...,NaN,42.0,34.0,NaN,NaN,0.218750,0.163462,NaN,NaN,4
199907,199907,2020-10-17 06:47:48.801538,3367,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 121], [1, 71], [3, 113], [4, 94], [6, 126...",1,61,68,0,17,...,220.0,50.0,19.0,49.0,2.0,0.260417,0.091787,0.241379,0.009091,8
199967,199967,2020-10-17 06:48:03.862978,790,"[1, 32, 33, 33, 29, 21, 27, 6, 7, 16, 17, 23]","[[0, 116], [1, 65], [3, 122], [4, 78], [6, 116...",1,48,59,0,13,...,NaN,51.0,44.0,42.0,NaN,0.281768,0.220000,0.221053,NaN,7

In [9]:
mdfo.keepEvents("asymL1", 0.28, "<=")
mdf1 = mdfo.events_df

In [10]:
mdf1

,event_num,event_time,deadtime,ADC,TDC,SCh0,SCh1,SCh2,SCh3,SCh4,...,sumL4,diffL1,diffL2,diffL3,diffL4,asymL1,asymL2,asymL3,asymL4,numLHit
139,139,2020-10-16 17:33:12.262549,839,"[1, 31, 33, 33, 29, 21, 27, 6, 7, 16, 16, 23]","[[0, 127], [1, 77], [3, 90], [4, 125], [9, 116...",1,28,27,0,9,...,231.0,50.0,-35.0,NaN,1.0,0.245098,-0.162791,NaN,0.004329,6
300,300,2020-10-16 17:33:54.416732,1104,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 115], [1, 73], [3, 126], [4, 82], [6, 115...",1,7,12,0,3,...,NaN,42.0,44.0,24.0,NaN,0.223404,0.211538,0.116505,NaN,7
467,467,2020-10-16 17:34:35.381299,1249,"[1, 32, 33, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 118], [1, 68], [3, 124], [4, 110], [6, 12...",1,15,29,0,5,...,251.0,50.0,14.0,41.0,3.0,0.268817,0.059829,0.201970,0.011952,8
495,495,2020-10-16 17:34:43.042057,3399,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 122], [1, 73], [3, 84], [4, 117], [9, 130]]",1,37,47,0,19,...,NaN,49.0,-33.0,NaN,NaN,0.251282,-0.164179,NaN,NaN,5
566,566,2020-10-16 17:35:02.334107,3326,"[1, 35, 36, 37, 33, 24, 30, 9, 10, 20, 20, 26]","[[0, 121], [1, 78], [3, 110], [4, 110], [6, 12...",1,56,77,0,18,...,NaN,43.0,0.0,33.0,NaN,0.216080,0.000000,0.159420,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199831,199831,2020-10-17 06:47:31.719531,3445,"[1, 31, 32, 33, 29, 21, 27, 6, 7, 16, 17, 23]","[[0, 127], [1, 77], [3, 89], [4, 123]]",1,45,85,0,17,...,NaN,50.0,-34.0,NaN,NaN,0.245098,-0.160377,NaN,NaN,4
199853,199853,2020-10-17 06:47:36.119947,1225,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 123], [1, 80], [3, 87], [4, 121], [6, 126...",1,28,27,0,4,...,215.0,43.0,-34.0,42.0,43.0,0.211823,-0.163462,0.200000,0.200000,8
199880,199880,2020-10-17 06:47:42.660912,1369,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 121], [1, 77], [3, 80], [4, 123], [6, 120...",1,28,35,0,17,...,208.0,44.0,-43.0,34.0,46.0,0.222222,-0.211823,0.165049,0.221154,8
199902,199902,2020-10-17 06:47:47.971304,819,"[1, 31, 32, 33, 29, 21, 27, 6, 7, 16, 16, 23]","[[0, 117], [1, 75], [3, 121], [4, 87]]",1,40,54,0,12,...,NaN,42.0,34.0,NaN,NaN,0.218750,0.163462,NaN,NaN,4
199907,199907,2020-10-17 06:47:48.801538,3367,"[1, 31, 32, 33, 29, 21, 26, 6, 7, 16, 16, 23]","[[0, 121], [1, 71], [3, 113], [4, 94], [6, 126...",1,61,68,0,17,...,220.0,50.0,19.0,49.0,2.0,0.260417,0.091787,0.241379,0.009091,8

In [ ]:
mdfo.getH