# Analysis of Lead Brick Experiment

In [5]:
from MuonDataFrame import *
file = "processed_data/events_data_frame_25.h5"
mdfo = MuonDataFrame(file, isNew=False, d1="last") #Muon Data Frame Object

In [6]:
mdfo.show()

,event_num,event_time,deadtime,ADC,TDC,l1hit,l2hit,l3hit,l4hit,r1hit,...,sumL4,diffL1,diffL2,diffL3,diffL4,asymL1,asymL2,asymL3,asymL4,numLHit
0,0,2020-11-15 21:25:40.485357,871,"[1, 33, 34, 35, 31, 22, 29, 8, 9, 18, 19, 25]","[[0, 111], [3, 117], [4, 90], [6, 112], [9, 11...",1.0,1.0,1.0,1.0,0.0,...,191.0,NaN,27.0,NaN,29.0,NaN,0.130435,NaN,0.151832,7
1,1,2020-11-15 21:25:40.575285,824,"[1, 33, 34, 35, 31, 22, 29, 8, 9, 18, 18, 25]","[[0, 117], [1, 92], [3, 93], [4, 119], [6, 110...",1.0,1.0,1.0,1.0,1.0,...,196.0,25.0,-26.0,9.0,54.0,0.119617,-0.122642,0.042654,0.275510,9
2,2,2020-11-15 21:25:40.865367,1174,"[1, 34, 34, 35, 31, 23, 29, 8, 9, 19, 19, 25]","[[3, 124], [4, 149], [12, 35]]",0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,-25.0,NaN,NaN,NaN,-0.091575,NaN,NaN,3
3,3,2020-11-15 21:25:41.165380,3463,"[1, 33, 34, 35, 31, 22, 29, 8, 9, 18, 19, 25]","[[1, 142], [6, 92], [7, 125], [12, 35]]",0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,-33.0,NaN,NaN,NaN,-0.152074,NaN,4
4,4,2020-11-15 21:25:41.675394,1192,"[1, 33, 34, 35, 31, 22, 29, 8, 9, 18, 18, 25]","[[0, 98], [1, 98], [3, 89], [4, 114], [7, 105]...",1.0,1.0,0.0,0.0,1.0,...,NaN,0.0,-25.0,NaN,NaN,0.000000,-0.123153,NaN,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499995,2020-11-17 15:40:23.122099,1223,"[1, 33, 34, 35, 31, 22, 28, 7, 8, 18, 18, 24]","[[1, 129], [3, 125], [4, 82], [6, 104], [7, 10...",0.0,1.0,1.0,0.0,1.0,...,NaN,NaN,43.0,0.0,NaN,NaN,0.207729,0.000000,NaN,7
499996,499996,2020-11-17 15:40:23.542365,1320,"[1, 33, 34, 35, 31, 22, 28, 7, 9, 18, 18, 24]","[[0, 107], [3, 120], [4, 84], [6, 105], [7, 97...",1.0,1.0,1.0,1.0,0.0,...,185.0,NaN,36.0,8.0,11.0,NaN,0.176471,0.039604,0.059459,8
499997,499997,2020-11-17 15:40:23.672175,883,"[1, 33, 34, 35, 31, 22, 28, 7, 9, 18, 18, 24]","[[0, 115], [1, 96], [3, 135], [4, 87], [6, 89]...",1.0,1.0,1.0,1.0,1.0,...,197.0,19.0,48.0,-33.0,47.0,0.090047,0.216216,-0.156398,0.238579,9
499998,499998,2020-11-17 15:40:24.101961,1112,"[1, 33, 34, 35, 31, 22, 28, 7, 8, 18, 18, 24]","[[1, 120], [3, 116], [6, 121], [12, 36]]",0.0,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
499999,499999,2020-11-17 15:40:24.342225,3087,"[1, 33, 34, 35, 31, 22, 28, 7, 9, 18, 18, 24]","[[0, 127], [1, 83], [3, 137], [7, 130], [9, 12...",1.0,1.0,0.0,1.0,1.0,...,196.0,44.0,NaN,NaN,46.0,0.209524,NaN,NaN,0.234694,7